
name: Android Debug APK
on: { workflow_dispatch: {}, push: { branches: [ main, master ] } }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: android-actions/setup-android@v3
      - uses: gradle/gradle-build-action@v2
        with: { gradle-version: 8.7, arguments: ":app:assembleDebug" }
      - uses: actions/upload-artifact@v4
        with: { name: elina-debug-apk, path: app/build/outputs/apk/debug/*.apk }
